version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yap-app-${COMPOSE_PROJECT_NAME}
    volumes:
      - yap-public:/var/www/public
      - yap-conf:/docker/nginx/conf.d
      # - ./public:/var/www/public
      # - ./:/var/www
      # - laravel-storage:/var/www/storage
      # - laravel-db:/var/www/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - yap-network

  webserver:
    image: nginx:alpine
    container_name: yap-nginx-${COMPOSE_PROJECT_NAME}
    ports:
      - "8081:80"
    volumes:
      - yap-public:/var/www/public
      - yap-conf:/etc/nginx/conf.d
        # - ./:/var/www
        # - ./public:/var/www/public
        # - ./docker/nginx/conf.d:/etc/nginx/conf.d
        # - /var/lib/docker/volumes/jenkins_home/_data/workspace/${COMPOSE_PROJECT_NAME}/public:/var/www/public
        # - /var/lib/docker/volumes/jenkins_home/_data/workspace/${COMPOSE_PROJECT_NAME}/docker/nginx/conf.d:/etc/nginx/conf.d
    # command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - yap-network

volumes:
  yap-public:
  yap-conf:

networks:
  yap-network:
    driver: bridge