version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yap-app-${COMPOSE_PROJECT_NAME}
    # volumes:
    #   - ./:/var/www
      # - laravel-storage:/var/www/storage
      # - laravel-db:/var/www/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - yap-network

  webserver:
    image: nginx:alpine
    container_name: yap-nginx-${COMPOSE_PROJECT_NAME}
    ports:
      - "8081:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        # - ./public:/var/www/public
        # - ./docker/nginx:/etc/nginx
        # - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf 
        # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - yap-network

# volumes:
#   laravel-db:
#   laravel-storage:

networks:
  yap-network:
    driver: bridge