version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yap-app-${COMPOSE_PROJECT_NAME}
    # volumes:
      # - ./public:/var/www/public
      # - ./:/var/www
      # - laravel-storage:/var/www/storage
      # - laravel-db:/var/www/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    networks:
      - yap-network

  webserver:
    image: nginx:alpine
    container_name: yap-nginx-${COMPOSE_PROJECT_NAME}
    ports:
      - "8081:80"
    volumes:
        # - ./:/var/www
        # - ./public:/var/www/public
        # - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - /var/lib/docker/volumes/jenkins_home/_data/workspace/${COMPOSE_PROJECT_NAME}/public:/var/www/public
        - /var/lib/docker/volumes/jenkins_home/_data/workspace/${COMPOSE_PROJECT_NAME}/docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - yap-network

# volumes:
#   laravel-db:
#   laravel-storage:

networks:
  yap-network:
    driver: bridge